function New-DocusaurusModuleHelp {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]    $Module,
        [Parameter(Mandatory)] [string]    $DocsFolder,
        [Parameter(Mandatory)] [string]    $SideBar,
        [string]    $EditUrl           = 'null',
        [string[]]  $Exclude           = @(),
        [string]    $MetaDescription   = 'Help page for the PowerShell %1 command',
        [string[]]  $MetaKeywords      = @('PowerShell', 'Help', 'Documentation'),
        [string]    $PrependMarkdown   = '',
        [string]    $AppendMarkdown    = '',
        [string]    $HelpVersion       = '',
        [hashtable] $CommandVersionMap = @{}
    )

    if (-not (Get-Module $Module)) {
        Import-Module $Module -Force
    }

    $tempDir = Join-Path ([System.IO.Path]::GetTempPath()) "platyps_$(Get-Random)"
    New-Item -ItemType Directory -Path $tempDir | Out-Null

    try {
        New-MarkdownCommandHelp -ModuleInfo (Get-Module $Module) -OutputFolder $tempDir -Force | Out-Null

        $moduleSubDir = Join-Path $tempDir $Module
        $mdFiles = Get-ChildItem -Path $moduleSubDir -Filter '*.md' |
                   Where-Object { $_.BaseName -notin $Exclude } |
                   Sort-Object BaseName

        $outputFolder = Join-Path $DocsFolder $SideBar
        $allCommandNames = $mdFiles | Select-Object -ExpandProperty BaseName
        $sidebarItems = [System.Collections.Generic.List[string]]::new()

        foreach ($mdFile in $mdFiles) {
            $commandName = $mdFile.BaseName

            $sinceBadge = ''
            if ($CommandVersionMap.ContainsKey($commandName)) {
                $sinceVersion = $CommandVersionMap[$commandName]
                $sinceBadge = @"
:::note Since $Module $sinceVersion
This command was introduced in $Module $sinceVersion and is not available in earlier versions.
:::
"@
            }

            $mdxSplat = @{
                SourceFile      = $mdFile
                CommandName     = $commandName
                MetaDescription = $MetaDescription
                MetaKeywords    = $MetaKeywords
                EditUrl         = $EditUrl
                PrependMarkdown = $PrependMarkdown
                AppendMarkdown  = $AppendMarkdown
                AllCommandNames = $allCommandNames
                SinceBadge      = $sinceBadge
                SideBar         = $SideBar
            }
            $mdxContent = ConvertTo-DocusaurusMdx @mdxSplat

            $outputPath = Join-Path $outputFolder "$commandName.mdx"
            Set-Content -Path $outputPath -Value $mdxContent -Encoding UTF8 -NoNewline
            Write-Host "  Generated: $commandName.mdx"

            $sidebarItems.Add("'$SideBar/$commandName'")
        }

        $sidebarEntries = ($sidebarItems | ForEach-Object { "    $_" }) -join ",`n"
        $sidebarContent = @"
/**
 * Import this file in your Docusaurus ``sidebars.js`` file.
 *
 * Auto-generated by New-DocusaurusModuleHelp using Microsoft.PowerShell.PlatyPS.
 */

module.exports = [
$sidebarEntries
];
"@
        $sidebarPath = Join-Path $outputFolder 'docusaurus.sidebar.js'
        Set-Content -Path $sidebarPath -Value $sidebarContent -Encoding UTF8 -NoNewline
        Write-Host "  Generated: docusaurus.sidebar.js ($($sidebarItems.Count) commands)"
    }
    finally {
        Remove-Item -Path $tempDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function ConvertTo-DocusaurusMdx {
    param(
        [System.IO.FileInfo] $SourceFile,
        [string]   $CommandName,
        [string]   $MetaDescription,
        [string[]] $MetaKeywords,
        [string]   $EditUrl,
        [string]   $PrependMarkdown,
        [string]   $AppendMarkdown,
        [string[]] $AllCommandNames,
        [string]   $SinceBadge = '',
        [string]   $SideBar = 'commands'
    )

    $raw = Get-Content -Path $SourceFile.FullName -Raw

    # Strip PlatyPS v2 frontmatter block
    $body = $raw -replace '(?s)^---.*?---\s*', ''

    # Strip the H1 title line PlatyPS emits
    $body = $body -replace '(?m)^# .+\r?\n', ''

    # Convert markdown parameter tables to yaml fenced blocks
    $body = Convert-ParameterTablesToYamlFences -Body $body

    # Wrap example code in powershell fenced blocks.
    # PlatyPS v2 outputs example code as plain text; detect the first paragraph of each
    # ### EXAMPLE section (before the first blank line) and wrap it. Skip if already fenced.
    $body = [System.Text.RegularExpressions.Regex]::Replace(
        $body,
        '(?m)^(### EXAMPLE [^\r\n]+)\r?\n\r?\n(?!```)([^\r\n][^\r\n]*(?:\r?\n(?!\r?\n)[^\r\n][^\r\n]*)*)',
        {
            param($m)
            $header = $m.Groups[1].Value
            $code   = $m.Groups[2].Value.TrimEnd()
            "$header`n`n``````powershell`n$code`n```````n"
        }
    )

    # Fix RELATED LINKS: [Name]() -> [Name](/docs/<sidebar>/Name) for known commands, strip unknown
    foreach ($cmd in $AllCommandNames) {
        $escaped = [regex]::Escape($cmd)
        $body = $body -replace "\[$escaped\]\(\)", "[$cmd](/docs/$SideBar/$cmd)"
    }
    $body = $body -replace '\[([^\]]+)\]\(\)', '$1'

    # Escape curly braces outside code fences (required for MDX/JSX compatibility)
    $body = Escape-CurlyBracesOutsideCodeFences -Body $body

    # Build Docusaurus frontmatter
    $description = $MetaDescription -replace '%1', $CommandName
    $keywordsYaml = ($MetaKeywords | ForEach-Object { "  - $_" }) -join "`n"
    $customEditUrl = if ($EditUrl -eq 'null') { 'null' } else { "$EditUrl/$CommandName.ps1" }

    $frontmatter = @"
---
id: $CommandName
title: $CommandName
description: $description
keywords:
$keywordsYaml
hide_title: false
hide_table_of_contents: false
custom_edit_url: $customEditUrl
---
"@

    $parts = [System.Collections.Generic.List[string]]::new()
    $parts.Add($frontmatter)
    if ($PrependMarkdown) { $parts.Add($PrependMarkdown.Trim()) }
    if ($SinceBadge)      { $parts.Add($SinceBadge.Trim()) }
    $parts.Add($body.Trim())
    if ($AppendMarkdown)  { $parts.Add($AppendMarkdown.Trim()) }

    return ($parts -join "`n`n") + "`n"
}

function Convert-ParameterTablesToYamlFences {
    param([string] $Body)

    # PlatyPS v2 emits yaml fenced blocks natively (keys: DefaultValue, ParameterSets, etc.)
    # These are already renderable — return body unchanged and skip table conversion.
    if ($Body -match '(?ms)^```yaml[\r\n]+(?:Type|DefaultValue):') {
        return $Body
    }

    # PlatyPS v1: convert markdown tables to yaml fences
    $result = [System.Text.RegularExpressions.Regex]::Replace(
        $Body,
        '(?ms)(### -\w[^\r\n]*\r?\n)(.*?)(?=### -|\z)',
        {
            param($match)
            $header  = $match.Groups[1].Value
            $content = $match.Groups[2].Value

            # Extract description text (everything before the first table row)
            $descText = ($content -split '(?m)^\|')[0].TrimEnd()

            # Helper: extract a value from a markdown table row by property name
            function Get-TableValue([string]$text, [string]$prop) {
                if ($text -match "(?m)^\|\s*$([regex]::Escape($prop))\s*\|\s*([^|]+)\|") {
                    return $matches[1].Trim()
                }
                return $null
            }

            $type      = Get-TableValue $content 'Type:'
            $mandatory = Get-TableValue $content 'Mandatory:'
            $position  = Get-TableValue $content 'Position:'
            $default   = Get-TableValue $content 'Default value:'
            $pipeline  = Get-TableValue $content 'Value from pipeline:'
            $wildcard  = Get-TableValue $content 'Supports wildcards:'
            $aliases   = Get-TableValue $content 'Aliases:'

            # Strip System. namespace prefix from types
            if ($type) { $type = $type -replace '^System\.', '' } else { $type = 'None' }

            $required = if ($mandatory -eq 'True') { 'True' } else { 'False' }

            # v2 position is 0-based; v1 (target) is 1-based
            if ($position -and $position -match '^\d+$') {
                $position = [int]$position + 1
            } elseif (-not $position) {
                $position = 'Named'
            }

            if (-not $default)   { $default  = 'None' }
            if (-not $pipeline)  { $pipeline = 'False' }
            if (-not $wildcard)  { $wildcard = 'False' }
            if (-not $aliases)   { $aliases  = '' }

            # Detect parameter sets - look for "Parameter sets" section in the content
            $paramSets = '(All)'
            if ($content -match '(?ms)Parameter sets\s*\r?\n\|[^\r\n]+\r?\n\|[^\r\n]+\r?\n\|\s*([^|]+)\|') {
                $paramSets = $matches[1].Trim()
            }

            $yamlFence = @"

``````yaml
Type: $type
Parameter Sets: $paramSets
Aliases: $aliases

Required: $required
Position: $position
Default value: $default
Accept pipeline input: $pipeline
Accept wildcard characters: $wildcard
``````

"@
            return $header + $descText + $yamlFence
        }
    )

    return $result
}

function Escape-CurlyBracesOutsideCodeFences {
    param([string] $Body)

    # Split on fenced code blocks (``` delimiters), alternating outside/inside
    $segments = [System.Text.RegularExpressions.Regex]::Split(
        $Body,
        '((?ms)^```[^\r\n]*\r?\n.*?^```\r?\n?)'
    )

    $result = for ($i = 0; $i -lt $segments.Count; $i++) {
        if ($i % 2 -eq 0) {
            # Outside a code fence — escape curly braces
            $segments[$i] -replace '\{', '\{' -replace '\}', '\}'
        } else {
            # Inside a code fence — pass through unchanged
            $segments[$i]
        }
    }

    return $result -join ''
}
